# Generated by Django 4.2 on 2023-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
