# Generated by Django 4.2 on 2023-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuyaTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablespaceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, db_tablespace='indexes', max_length=30)),
                ('data', models.CharField(db_index=True, max_length=255)),
                ('shortcut', models.CharField(max_length=7)),
                ('edges', models.ManyToManyField(db_tablespace='indexes', to='ayuyaTest.tablespaceexample')),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.AddIndex(
            model_name='tablespaceexample',
            index=models.Index(db_tablespace='other_indexes', fields=['shortcut'], name='ayuyaTest_t_shortcu_8db010_idx'),
        ),
    ]
