# Generated by Django 4.1.7 on 2023-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tce_sessions',
            fields=[
                ('cpsession_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cpsession_expiry', models.DateTimeField()),
                ('cpsession_data', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tce_users',
            fields=[
                ('user_id', models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_regdate', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=40)),
                ('user_firstname', models.CharField(max_length=255)),
                ('user_lastname', models.CharField(max_length=255)),
                ('user_birthdate', models.DateField()),
                ('user_birthplace', models.CharField(max_length=255)),
                ('user_regnumber', models.CharField(max_length=255, unique=True)),
                ('user_ssn', models.CharField(max_length=255, unique=True)),
                ('user_level', models.SmallIntegerField()),
                ('user_verifycode', models.CharField(max_length=255, unique=True)),
                ('user_otpkey', models.CharField(max_length=255)),
            ],
        ),
    ]
