# Generated by Django 4.1.7 on 2023-04-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0003_tce_modules_tce_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='tce_questions',
            fields=[
                ('question_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('question_description', models.TextField()),
                ('question_explanation', models.TextField(default='null', null=True)),
                ('question_type', models.SmallIntegerField(default=1)),
                ('question_difficulty', models.SmallIntegerField(default=1)),
                ('question_enabled', models.BooleanField(default=0)),
                ('question_position', models.BigIntegerField(default=0)),
                ('question_timer', models.SmallIntegerField(default=0)),
                ('question_fullscreen', models.BooleanField(default=False)),
                ('question_inline_answers', models.BooleanField(default=0)),
                ('question_auto_next', models.BooleanField(default=False)),
                ('question_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_test.tce_subjects')),
            ],
        ),
    ]
