# Generated by Django 4.1.7 on 2023-04-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0007_alter_tce_modules_module_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_answers',
            name='answer_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_test.tce_questions'),
        ),
        migrations.CreateModel(
            name='tce_tests',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255, unique=True)),
                ('test_description', models.TextField()),
                ('test_begin_time', models.DateTimeField(default='')),
                ('test_end_time', models.DateTimeField()),
                ('test_duration_time', models.SmallIntegerField(default=0)),
                ('test_ip_range', models.CharField(default='*.*.*.*', max_length=255)),
                ('test_results_to_users', models.BooleanField(default=False)),
                ('test_report_to_users', models.BooleanField(default=False)),
                ('test_score_right', models.SmallIntegerField(default=1)),
                ('test_score_wrong', models.SmallIntegerField(default=0)),
                ('test_score_unanswered', models.SmallIntegerField(default=0)),
                ('test_max_score', models.SmallIntegerField(default=0)),
                ('test_score_threshold', models.SmallIntegerField(default=0)),
                ('test_random_questions_select', models.BooleanField(default=True)),
                ('test_random_questions_order', models.BooleanField(default=True)),
                ('test_questions_order_mode', models.SmallIntegerField(default=0)),
                ('test_comment_enabled', models.BooleanField(default=True)),
                ('test_menu_enabled', models.BooleanField(default=True)),
                ('test_noanswer_enabled', models.BooleanField(default=True)),
                ('test_mcma_enabled', models.BooleanField(default=True)),
                ('test_repeatable', models.SmallIntegerField(default=0)),
                ('test_mcma_partial_score', models.BooleanField(default=True)),
                ('test_logout_on_timeout', models.BooleanField(default=False)),
                ('test_password', models.CharField(default='', max_length=255, null=True)),
                ('test_user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls_test.tce_users')),
            ],
        ),
    ]
