# Generated by Django 4.2 on 2023-04-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0010_alter_tce_tests_logs_testlog_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_tests_users',
            name='testuser_comment',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='tce_tsets_users',
        ),
    ]
