# Generated by Django 4.2 on 2023-04-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0011_alter_tce_tests_users_testuser_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_users',
            name='user_ip',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
