# Generated by Django 4.2 on 2023-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0012_alter_tce_users_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_users',
            name='user_ip',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_otpkey',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_verifycode',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
