# Generated by Django 4.2 on 2023-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0014_alter_tce_tests_users_testuser_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_answers',
            name='answer_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tce_answers',
            name='answer_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tce_questions',
            name='question_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tce_questions',
            name='question_explanation',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AlterField(
            model_name='tce_subjects',
            name='subject_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tce_tests',
            name='test_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tce_tests',
            name='test_ip_range',
            field=models.CharField(blank=True, default='*.*.*.*', max_length=255),
        ),
        migrations.AlterField(
            model_name='tce_tests_users',
            name='testuser_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_birthplace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_ip',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_otpkey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_ssn',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tce_users',
            name='user_verifycode',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
