# Generated by Django 4.2 on 2023-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0015_alter_tce_answers_answer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_test_subject_set',
            name='tsubset_difficulty',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
