# Generated by Django 4.2 on 2023-04-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0016_alter_tce_test_subject_set_tsubset_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_tests',
            name='test_repeatable',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
    ]
