# Generated by Django 4.2 on 2023-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0018_alter_tce_tests_test_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tce_tests',
            constraint=models.CheckConstraint(check=models.Q(('test_password__length__gte', 8)), name='polls_test_tce_tests_title_length'),
        ),
        migrations.AddConstraint(
            model_name='tce_users',
            constraint=models.CheckConstraint(check=models.Q(('user_password__length__gte', 8)), name='polls_test_tce_users_title_length'),
        ),
    ]
