# Generated by Django 4.2 on 2023-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0021_remove_tce_users_polls_test_tce_users_title_length_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tce_tests',
            name='polls_test_tce_tests_password_length',
        ),
        migrations.RemoveConstraint(
            model_name='tce_users',
            name='polls_test_tce_users_users_length',
        ),
        migrations.AlterField(
            model_name='tce_tests',
            name='test_password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='tce_tests',
            constraint=models.CheckConstraint(check=models.Q(('test_password__length__gte', 8)), name='polls_test_tce_tests_tce_test_length'),
        ),
        migrations.AddConstraint(
            model_name='tce_users',
            constraint=models.CheckConstraint(check=models.Q(('user_password__length__gte', 8)), name='polls_test_tce_users_tce_users_length'),
        ),
    ]
