# Generated by Django 4.2 on 2023-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0022_remove_tce_tests_polls_test_tce_tests_password_length_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tce_tests',
            name='polls_test_tce_tests_tce_test_length',
        ),
        migrations.RemoveConstraint(
            model_name='tce_users',
            name='polls_test_tce_users_tce_users_length',
        ),
        migrations.AddConstraint(
            model_name='tce_tests',
            constraint=models.CheckConstraint(check=models.Q(('test_password__length__gte', 8)), name='tce_test_length'),
        ),
        migrations.AddConstraint(
            model_name='tce_users',
            constraint=models.CheckConstraint(check=models.Q(('user_password__length__gte', 8)), name='tce_users_length'),
        ),
    ]
