# Generated by Django 4.2 on 2023-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0023_remove_tce_tests_polls_test_tce_tests_tce_test_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_tests',
            name='test_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
