# Generated by Django 4.2 on 2023-04-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0024_alter_tce_tests_test_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_Name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_fullname', models.CharField(max_length=100, verbose_name='Student Name')),
                ('student_Department', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tce_tests',
            name='test_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Exit exam Test Name'),
        ),
        migrations.AlterField(
            model_name='tce_testsslcerts',
            name='tstssl_test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_test.tce_tests', verbose_name='Test SSl configuration'),
        ),
        migrations.CreateModel(
            name='taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('taken_year', models.PositiveIntegerField(verbose_name='Academic Year')),
                ('course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_test.course')),
                ('student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_test.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student_Id',
            field=models.ManyToManyField(through='polls_test.taken', to='polls_test.student'),
        ),
    ]
