# Generated by Django 4.2 on 2023-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0025_course_student_alter_tce_tests_test_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taken',
            constraint=models.UniqueConstraint(fields=('taken_semester', 'taken_year', 'student_Id', 'course_Id'), name='crsstsID'),
        ),
    ]
