# Generated by Django 4.2 on 2023-04-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0027_alter_taken_taken_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taken',
            options={'ordering': ['course_Id']},
        ),
    ]
