# Generated by Django 4.2 on 2023-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0028_alter_taken_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_employee',
            fields=[
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('employee_age', models.PositiveIntegerField(default=20)),
                ('employee_salary', models.FloatField(default=2500.0, verbose_name='Employee Salary ')),
                ('duration_month', models.PositiveIntegerField(default=12)),
                ('allowance', models.PositiveIntegerField()),
                ('possible_extension', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='taken',
            options={'ordering': ['student_Id']},
        ),
    ]
