# Generated by Django 4.1.1 on 2023-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0030_permanent_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='retired_employee',
            fields=[
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': '',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls_test.contract_employee',),
        ),
        migrations.AlterField(
            model_name='contract_employee',
            name='allowance',
            field=models.PositiveIntegerField(default=3000, null=True),
        ),
    ]
