# Generated by Django 4.1.1 on 2023-04-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0031_retired_employee_alter_contract_employee_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Engineer', max_length=100)),
                ('job_grade', models.PositiveSmallIntegerField(default=10)),
                ('salary', models.FloatField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='emp_collection',
            fields=[
                ('permanent_employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='polls_test.permanent_employee')),
                ('employee_salary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls_test.employee_salary')),
            ],
            options={
                'abstract': False,
            },
            bases=('polls_test.employee_salary', 'polls_test.permanent_employee'),
        ),
        migrations.AddConstraint(
            model_name='employee_salary',
            constraint=models.UniqueConstraint(fields=('job_grade', 'job_title'), name='salaryScale'),
        ),
    ]
