# Generated by Django 4.1.1 on 2023-04-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_test', '0033_alter_retired_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce_users',
            name='user_verifycode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
